Repository wecode-bootcamp-korea/41-2nd-PetWithU-frontend, pull requests merged in 2023-02, with the labels that each got.

#4 [41기-배경민] Add : feed layout구현 완료
  public/data/feedData.json
  public/data/rightData.json
  public/images/123.png
  public/images/image.png
  src/pages/Feed/Feed.js
  src/pages/Feed/Feed.styles.js
Labels: 완료

#12 [41기-배경민] Feature/nav
  src/components/Nav/Nav.js
  src/components/Nav/Nav.styles.js
  src/components/Search/Search.js
  src/components/Search/Search.styles.js
  src/components/Search/SearchList.js
Labels: 멘토 리뷰 요청

#14 [41기-배경민] Add : main layout 구현
  public/data/mainData.json
  src/pages/Main/Main.js
  src/pages/Main/Main.styles.js
Labels: 완료

#9 [41기 권나현]ADD: product detail페이지 레이아웃 & 기능추가
  src/pages/Detail/CommonDetail/ProductContentBottom.jsx
  src/pages/Detail/CommonDetail/ProductContentContainer.jsx
  src/pages/Detail/CommonDetail/ProductContentTop.jsx
  src/pages/Detail/CommonDetail/ProductDetail.jsx
  src/pages/Detail/CommonDetail/ProductDetailStyle.js
  src/pages/Detail/CommonDetail/ProductImgBox.jsx
Labels: 멘토 리뷰 요청, 수정 요청

#18 [41기 배경민] Modify : 로그인 api주소 변경 및 레이아웃 수정
  src/pages/Login/KakaoLogin.js
  src/pages/Login/Login.js
  src/pages/Login/Login.styles.js
Labels: 멘토 리뷰 요청

#21 [41기 배경민] Add : customHooks 제공
  src/Hooks/usePostState.js
Labels: 멘토 리뷰 요청

#22 [41기 권나현]ADD: feedDetail페이지 레이아웃 구현
  src/pages/Feed/FeedDetail/FeedDetail.jsx
  src/pages/Feed/FeedDetail/FeedDetailMain.jsx
  src/pages/Feed/FeedDetail/FeedDetailRight.jsx
  src/pages/Feed/FeedDetail/FeedDetailStyle.js
  src/pages/Feed/FeedDetail/FeedReview.jsx
  src/pages/Feed/FeedDetail/FeedReviewList.jsx
Labels: 완료

#19 [41기 배경민] Add : 스크랩페이지 레이아웃 및 백통신 준비
  src/Router.js
  src/pages/ScrapPage/FeedScrap.js
  src/pages/ScrapPage/MapScrap.js
  src/pages/ScrapPage/ScrapPage.js
  src/pages/ScrapPage/ScrapPage.styles.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#10 [41기 권나현]cart페이지 레이아웃 & 기능 추가
  src/pages/Cart/Cart.js
  src/pages/Cart/CartLeft.jsx
  src/pages/Cart/CartList.jsx
  src/pages/Cart/CartRight.jsx
  src/pages/Cart/CartStyle.js
  src/pages/Cart/hooks/useCart.jsx
Labels: 완료

#13 [41기 배경민] Add : feed Item 기능 구현 및 페이지 네이션 구현
  package-lock.json
  package.json
  public/data/feedData.json
  public/images/heart.png
  src/components/Nav/Nav.js
  src/pages/Feed/Feed.js
  src/pages/Feed/Feed.styles.js
  src/pages/Feed/FeedBtnList.js
  src/pages/Feed/FeedItem.js
  src/pages/Feed/FeedPoints.js
  src/pages/Feed/FeedSlideBox.js
  src/pages/Feed/FeedSlideBox.styles.js
  src/pages/Feed/Modal.js
  src/pages/Feed/Modal.styles.js
  src/pages/Login/KakaoLogin.js
Labels: 멘토 리뷰 요청

#11 [41기 권나현]Feature/community
  package-lock.json
  package.json
  public/data.json
  public/mock/Data.json
  public/mock/detail.json
  public/mock/mock.json
  src/pages/Community/Community.js
  src/pages/Community/CommunityContainer.jsx
  src/pages/Community/CommunityForm.jsx
  src/pages/Community/CommunityHashTag.jsx
  src/pages/Community/CommunityImg.jsx
  src/pages/Community/CommunityImgItem.jsx
  src/pages/Community/CommunitySearch.jsx
  src/pages/Community/CommunityStyle.js
Labels: 수정 요청
